spring:
  application:
    name: "configserver"
  profiles:
   # active: native
    active: git
  cloud:
    config:
      server:
        #native:
         # search-locations: "classpath:/config"
        git:
          uri: "https://github.com/SahoreUjjwal/configMicroservice.git"
          default-label: develop #branch
          timeout: 5 #in seconds
          clone-on-start: true
          force-pull: true # will pull on start of server
encrypt:
  key: "45D81JD23JSDF81DSA9231C93N3"
server:
  port: 8071
